/***** MUMBAI REAL ESTATE DATA ANALYSIS *****/ 

-- Dimension tables used in this analysis are:-

SELECT *
FROM DIM_FURNISH;

SELECT *
FROM DIM_PROPERTY_TYPE;

/*************** ANALYSIS PART ***********/


-- Q1. What were the minimum & maximum rents for 2BHK and 3BHK under residential apartments & serviced apartments in every city?

WITH RENT_PRICE_FOR_2_3_BHK AS
	(
		SELECT LABEL AS PROPERTY_LABEL,CITY,PREFERENCE,NUMBERS_OF_BEDROOM,TOTAL_PRICE,
			FIRST_VALUE(TOTAL_PRICE) OVER (PARTITION BY CITY,PROPERTY_LABEL,NUMBERS_OF_BEDROOM 
										   ORDER BY TOTAL_PRICE DESC) AS MAX_RENT_PRICE_FOR_2_3_BHK,
			LAST_VALUE(TOTAL_PRICE) OVER (PARTITION BY CITY,PROPERTY_LABEL,NUMBERS_OF_BEDROOM
										  ORDER BY TOTAL_PRICE DESC) AS MIN_RENT_PRICE_FOR_2_3_BHK
		FROM MUMBAI_REAL_ESTATE_FD JOIN DIM_PROPERTY_TYPE ON MUMBAI_REAL_ESTATE_FD.PROPERTY_TYPE_ID = DIM_PROPERTY_TYPE.ID
		WHERE NUMBERS_OF_BEDROOM IN ('2 BHK','3 BHK') AND PROPERTY_LABEL IN ('Residential Apartment','Serviced Apartments')
		AND PREFERENCE = 'Rent'
	)
SELECT DISTINCT CITY,PROPERTY_LABEL,PREFERENCE,
                NUMBERS_OF_BEDROOM,
				MIN_RENT_PRICE_FOR_2_3_BHK,
				MAX_RENT_PRICE_FOR_2_3_BHK
FROM RENT_PRICE_FOR_2_3_BHK
ORDER BY CITY ;


-- Q2. What was the minimum & maximum sales price for 2BHK, 4BHK under Residential Apartment & Serviced Apartments for each city.

WITH SALE_PRICE_FOR_2_4_BHK AS
	(
		SELECT LABEL AS PROPERTY_LABEL,CITY,PREFERENCE,NUMBERS_OF_BEDROOM,MAX_PRICE,
			FIRST_VALUE(MAX_PRICE) OVER (PARTITION BY CITY,PROPERTY_LABEL,NUMBERS_OF_BEDROOM 
										   ORDER BY TOTAL_PRICE DESC) AS MAX_SALE_PRICE_FOR_2_4_BHK,
			LAST_VALUE(MIN_PRICE) OVER (PARTITION BY CITY,PROPERTY_LABEL,NUMBERS_OF_BEDROOM
										  ORDER BY TOTAL_PRICE DESC) AS MIN_SALE_PRICE_FOR_2_4_BHK
		FROM MUMBAI_REAL_ESTATE_FD JOIN DIM_PROPERTY_TYPE ON MUMBAI_REAL_ESTATE_FD.PROPERTY_TYPE_ID = DIM_PROPERTY_TYPE.ID
		WHERE NUMBERS_OF_BEDROOM IN ('2 BHK','4 BHK') AND PROPERTY_LABEL IN ('Residential Apartment','Serviced Apartments')
		AND PREFERENCE = 'Sale'
	)
SELECT DISTINCT CITY,PROPERTY_LABEL,PREFERENCE,
                NUMBERS_OF_BEDROOM,
				MIN_SALE_PRICE_FOR_2_4_BHK,
                MAX_SALE_PRICE_FOR_2_4_BHK
FROM SALE_PRICE_FOR_2_4_BHK
ORDER BY CITY ;


-- Q3. what are the minimum & maximum sale price of Residential Land & Farm House in each city.

SELECT X.CITY,PROPERTY_LABEL,PREFERENCE,
	MIN_SALE_PRICE_FOR_RESDINTIAL_FARM_HOUSE,
	MAX_SALE_PRICE_FOR_RESDINTIAL_FARM_HOUSE
FROM
	(
		SELECT DISTINCT CITY,LABEL AS PROPERTY_LABEL,PREFERENCE,
		FIRST_VALUE(MAX_PRICE) OVER (PARTITION BY CITY,PROPERTY_LABEL ORDER BY MAX_PRICE DESC) AS MAX_SALE_PRICE_FOR_RESDINTIAL_FARM_HOUSE,
		LAST_VALUE(MAX_PRICE) OVER (PARTITION BY CITY,PROPERTY_LABEL ORDER BY MIN_PRICE DESC) AS MIN_SALE_PRICE_FOR_RESDINTIAL_FARM_HOUSE
		FROM MUMBAI_REAL_ESTATE_FD JOIN DIM_PROPERTY_TYPE ON MUMBAI_REAL_ESTATE_FD.PROPERTY_TYPE_ID = DIM_PROPERTY_TYPE.ID
		WHERE PROPERTY_LABEL IN ('Residential Land','Farm House') AND PREFERENCE = 'Sale'
	) X;


-- Q4. What are the rental charges for 2 BHK & 4 BHK for residential apartments & Serviced Apartments with furnished amenities?

SELECT DISTINCT CITY,DIM_PROPERTY_TYPE.LABEL AS PROPERTY_LABEL,PREFERENCE,
                NUMBERS_OF_BEDROOM,DIM_FURNISH.LABEL AS FURNISH_LABEL,
                FIRST_VALUE(TOTAL_PRICE) OVER (PARTITION BY CITY,PROPERTY_LABEL,NUMBERS_OF_BEDROOM ORDER BY TOTAL_PRICE ASC) AS MIN_RENT_PRICE,
               LAST_VALUE(TOTAL_PRICE) OVER (PARTITION BY CITY,PROPERTY_LABEL,NUMBERS_OF_BEDROOM ORDER BY TOTAL_PRICE ASC) AS MAX_RENT_PRICE
FROM MUMBAI_REAL_ESTATE_FD JOIN DIM_PROPERTY_TYPE ON MUMBAI_REAL_ESTATE_FD.PROPERTY_TYPE_ID = DIM_PROPERTY_TYPE.ID
JOIN DIM_FURNISH ON MUMBAI_REAL_ESTATE_FD.FURNISH_ID = DIM_FURNISH.ID
WHERE NUMBERS_OF_BEDROOM IN ('2 BHK','4 BHK') 
AND PREFERENCE = 'Rent'
AND PROPERTY_LABEL IN ('Residential Apartment','Serviced Apartments')
ORDER BY CITY ;


/* Q5. What is the price range for Independent House/Villa, Studio Apartment & Independent/Builder Floor in terms of minimum and maximum 
sale prices within your current property listings in each city. */ 

WITH CTE AS
	(
		SELECT CITY,LABEL AS PROPERTY_LABEL,PREFERENCE,
		NUMBERS_OF_BEDROOM,MIN_PRICE,MAX_PRICE
		FROM MUMBAI_REAL_ESTATE_FD
		JOIN DIM_PROPERTY_TYPE ON MUMBAI_REAL_ESTATE_FD.PROPERTY_TYPE_ID = DIM_PROPERTY_TYPE.ID
		WHERE PREFERENCE = 'Sale' AND PROPERTY_LABEL IN ('Independent House/Villa','Studio Apartment','Independent/Builder Floor')
	)
SELECT DISTINCT CITY,PROPERTY_LABEL,PREFERENCE,NUMBERS_OF_BEDROOM,
	LAST_VALUE(MIN_PRICE) OVER (PARTITION BY CITY,PROPERTY_LABEL ORDER BY MIN_PRICE DESC) AS MIN_SALE_PRICE,
	FIRST_VALUE(MAX_PRICE) OVER (PARTITION BY CITY,PROPERTY_LABEL ORDER BY MAX_PRICE DESC) AS MAX_SALE_PRICE
FROM CTE
ORDER BY CITY;